// 강의 예약하기
POST /reservation HTTP/1.1
Authorization: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIyIiwicm9sZXMiOlsiU1RVREVOVCJdLCJpYXQiOjE2MTU3NDI5NTMsImV4cCI6MTYxNTc0NjU1M30.PPrkLaATILYoy04tzeCTfqokjDsRmh_WBQYLoMoLqSg
IsRefreshToken: false
Content-Type: application/json;charset=UTF-8
Content-Length: 213
Host: localhost:8080

{
  "scheduleId" : 3,
  "reservationDateList" : [ {
    "date" : "2021-03-09",
    "time" : "05:00:00"
  } ],
  "equipmentList" : [ "오리발", "슈트" ],
  "description" : "발 사이즈 260, 옷 사이즈 L"
}