// 강의 예약하기
POST /reservation HTTP/1.1
Authorization: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiI1OCIsInJvbGVzIjpbIlNUVURFTlQiXSwiaWF0IjoxNjE1NTUzMTYyLCJleHAiOjE2MTU1NTY3NjJ9.YOhpXv8rmD1kbysM-vAKiixxzkyJD2nuvq23nUuT3vY
IsRefreshToken: false
Content-Type: application/json;charset=UTF-8
Content-Length: 213
Host: localhost:8080

{
  "scheduleId" : 52,
  "reservationDateList" : [ {
    "date" : "2021-03-25",
    "time" : "05:00:00"
  } ],
  "equipmentList" : [ "오리발", "슈트" ],
  "description" : "발 사이즈 260, 옷 사이즈 L"
}