// 강의 일정 생성
POST /schedule HTTP/1.1
Content-Type: application/json;charset=UTF-8
Authorization: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIyIiwicm9sZXMiOlsiU1RVREVOVCJdLCJpYXQiOjE2MTYzMTk0MTYsImV4cCI6MTYxNjMyMzAxNn0.Zf_WF-I5s46SkZok3fonyqKfY-togk4SzHgzqBkWins
IsRefreshToken: false
Content-Length: 752
Host: localhost:8080

{
  "lectureId" : 3,
  "period" : 3,
  "maxNumber" : 5,
  "detailReqList" : [ {
    "date" : "2021-03-25",
    "startTimes" : [ "13:00:00", "15:00:00" ],
    "lectureTime" : "01:30:00",
    "location" : {
      "latitude" : 37.0,
      "longitude" : 127.0,
      "address" : "상세 주소"
    }
  }, {
    "date" : "2021-03-26",
    "startTimes" : [ "13:00:00", "15:00:00" ],
    "lectureTime" : "01:30:00",
    "location" : {
      "latitude" : 37.0,
      "longitude" : 127.0,
      "address" : "상세 주소"
    }
  }, {
    "date" : "2021-03-27",
    "startTimes" : [ "13:00:00", "15:00:00" ],
    "lectureTime" : "01:30:00",
    "location" : {
      "latitude" : 37.0,
      "longitude" : 127.0,
      "address" : "상세 주소"
    }
  } ]
}

###

// 강의 일정 목록 읽기
GET /schedule?lectureId=3 HTTP/1.1
Content-Type: application/json;charset=UTF-8
Authorization: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIyIiwicm9sZXMiOlsiU1RVREVOVCJdLCJpYXQiOjE2MTYyNDE5NjYsImV4cCI6MTYxNjI0NTU2Nn0.cMWKi-Habwram10JenxBxOGwmi7CL_wEE1m-pPmskxM
IsRefreshToken: false
Host: localhost:8080
###

