const types = {
  RESERVATION_SELECT: 'RESERVATION_SELECT',
  RESERVATION_INIT: 'RESERVATION_INIT',
  RESERVATION_SELECT_EQUIPMENT: 'RESERVATION_SELECT_EQUIPMENT',
  RESERVATION_INIT_EQUIPMENT: 'RESERVATION_INIT_EQUIPMENT',
  RESERVATION_DESCRIPTION: 'RESERVATION_DESCRIPTION',
  RESERVATION_INIT_DESCRIPTION: 'RESERVATION_INIT_DESCRIPTION',
  RESERVATION_SCHEDULE_ID: 'RESERVATION_SCHEDULE_ID',
  RESERVATION_INIT_SCHEDULE_ID: 'RESERVATION_INIT_SCHEDULE_ID',

  // STUDENT_MYLIST_SET:'STUDENT_MYLIST_SET',
};

export default types;